// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOEgOc23NTGOxW0iRrwOcmvUAWkbP-3mY',
    appId: '1:806503611323:web:51dfb26ddc2d4d3a4f629e',
    messagingSenderId: '806503611323',
    projectId: 'engsoft-loja-cafe',
    authDomain: 'engsoft-loja-cafe.firebaseapp.com',
    storageBucket: 'engsoft-loja-cafe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZsFwmBRQC6a2TRAMIMt6AeTR0lWdwbZM',
    appId: '1:806503611323:android:6d46aa8e0ed3e41c4f629e',
    messagingSenderId: '806503611323',
    projectId: 'engsoft-loja-cafe',
    storageBucket: 'engsoft-loja-cafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUdBjnztQjT0CRtoLri9svnCO2dk3q8RU',
    appId: '1:806503611323:ios:c31c0d30cf0d0e794f629e',
    messagingSenderId: '806503611323',
    projectId: 'engsoft-loja-cafe',
    storageBucket: 'engsoft-loja-cafe.appspot.com',
    iosClientId: '806503611323-em0sib4c50hdk5entbkiokmdujrfnr05.apps.googleusercontent.com',
    iosBundleId: 'com.example.app05LojaCafe',
  );
}
